let skulltulas = [
  {id: 1, title: 'Behind the Know-It-All Brothers\' House', location: 'Kokiri Forest', young: true, adult: false, night: true, content: 'Descrption of Skulltula 1'},
  {id: 2, title: 'Soil by the Shop', location: 'Kokiri Forest', young: true, adult: false, night: false, content: 'Descrption of Skulltula 2'},
  {id: 3, title: 'Atop the House of Twins', location: 'Kokiri Forest', young: false, adult: true, night: true, content: 'Descrption of Skulltula 3'},
  {id: 4, title: 'Soil by the Bridge', location: 'Lost Woods', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 5, title: 'Soil in the Hidden Meadow', location: 'Lost Woods', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 6, title: 'High in the Hidden Meadow', location: 'Lost Woods', young: false, adult: true, night: true, content: 'Descrption of Skulltula 1'},
  {id: 7, title: 'High in the Sacred Forest Meadow', location: 'Sacred Forest Meadow', young: false, adult: true, night: true, content: 'Descrption of Skulltula 2'},
  {id: 8, title: 'Alcove in the Compass Room', location: 'Inside The Deku Tree', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 9, title: 'Vines in the Basement', location: 'Inside The Deku Tree', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 10, title: 'Grate in the Basement', location: 'Inside The Deku Tree', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 11, title: 'Secret Room Behind the Wall', location: 'Inside The Deku Tree', young: true, adult: false, night: false, content: 'Descrption of Skulltula 1'},
  {id: 12, title: 'Secret Grotto Near the Village', location: 'Hyrule Field', young: true, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 13, title: 'Ring of Rocks Near the Valley', location: 'Hyrule Field', young: true, adult: true, night: false, content: 'Descrption of Skulltula 3'},
  {id: 14, title: 'Guardhouse by the Market', location: 'Hyrule Town Market', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 15, title: 'Tree by the Gate', location: 'Hyrule Castle', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 16, title: 'Secret Grotto by the Moat', location: 'Hyrule Castle', young: true, adult: false, night: false, content: 'Descrption of Skulltula 1'},
  {id: 17, title: 'Behind the Ruined Gate', location: 'Ganon\'s Castle Grounds', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 18, title: 'Tree By Talon\'s House', location: 'Lon Lon Ranch', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 19, title: 'Behind the Feeding Shelter', location: 'Lon Lon Ranch', young: true, adult: false, night: true, content: 'Descrption of Skulltula 4'},
  {id: 20, title: 'Upper Window of Talon\'s House', location: 'Lon Lon Ranch', young: true, adult: false, night: true, content: 'Descrption of Skulltula 5'},
  {id: 21, title: 'High Fence by the Silo', location: 'Lon Lon Ranch', young: true, adult: false, night: true, content: 'Descrption of Skulltula 1'},
  {id: 22, title: 'Tree by the Entrance', location: 'Kakariko Village', young: true, adult: false, night: true, content: 'Descrption of Skulltula 2'},
  {id: 23, title: 'Side of the House of Skulltula', location: 'Kakariko Village', young: true, adult: false, night: true, content: 'Descrption of Skulltula 3'},
  {id: 24, title: 'Amongst the Construction', location: 'Kakariko Village', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 25, title: 'By the Gate to Death Mountain Trail', location: 'Kakariko Village', young: true, adult: false, night: true, content: 'Descrption of Skulltula 5'},
  {id: 26, title: 'On the Lookout Tower', location: 'Kakariko Village', young: true, adult: false, night: true, content: 'Descrption of Skulltula 1'},
  {id: 27, title: 'Roof of Impa\'s House', location: 'Kakariko Village', young: false, adult: true, night: true, content: 'Descrption of Skulltula 2'},
  {id: 28, title: 'Wall Near the Royal Family\'s Tomb', location: 'Graveyard', young: true, adult: false, night: true, content: 'Descrption of Skulltula 3'},
  {id: 29, title: 'Soil in the Graveyard', location: 'Graveyard', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 30, title: 'Soil by Dodongo\'s Cavern', location: 'Death Mountain Trail', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 31, title: 'Suspicious Wall Along the Trail', location: 'Death Mountain Trail', young: true, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 32, title: 'Red Rock Overlooking Dodongo\'s Cavern', location: 'Death Mountain Trail', young: false, adult: true, night: true, content: 'Descrption of Skulltula 2'},
  {id: 33, title: 'Red Rock Towards the Crater', location: 'Death Mountain Trail', young: false, adult: true, night: true, content: 'Descrption of Skulltula 3'},
  {id: 34, title: 'Among the Many Rocks', location: 'Goron City', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 35, title: 'Behind the Goron\'s Ruby\'s Platform', location: 'Goron City', young: false, adult: true, night: true, content: 'Descrption of Skulltula 5'},
  {id: 36, title: 'Crate by the Entrance', location: 'Death Mountain Crater', young: true, adult: false, night: false, content: 'Descrption of Skulltula 1'},
  {id: 37, title: 'Soil in the Crater', location: 'Death Mountain Crater', young: true, adult: false, night: false, content: 'Descrption of Skulltula 2'},
  {id: 38, title: 'Hidden Room by the Baby Dodongos', location: 'Dodongo\'s Cavern', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 39, title: 'On the Vines by the Staircase', location: 'Dodongo\'s Cavern', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 40, title: 'Hidden Room inside the Skull', location: 'Dodongo\'s Cavern', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 41, title: 'Alcove Atop the Raised Staircase', location: 'Dodongo\'s Cavern', young: true, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 42, title: 'Overlooking the Baby Dodongos', location: 'Dodongo\'s Cavern', young: true, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 43, title: 'Tree Past the Boulders', location: 'Zora\'s River', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 44, title: 'Ladder at the Top of the River', location: 'Zora\'s River', young: true, adult: false, night: true, content: 'Descrption of Skulltula 4'},
  {id: 45, title: 'High on the South Wall', location: 'Zora\'s River', young: false, adult: true, night: true, content: 'Descrption of Skulltula 5'},
  {id: 46, title: 'High up by the Bridge', location: 'Zora\'s River', young: false, adult: true, night: true, content: 'Descrption of Skulltula 1'},
  {id: 47, title: 'Wall by the Diving Game', location: 'Zora\'s Domain', young: false, adult: true, night: true, content: 'Descrption of Skulltula 2'},
  {id: 48, title: 'Tree by the Great Fairy', location: 'Zora\'s Fountain', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 49, title: 'Wall by the Giant Log', location: 'Zora\'s Fountain', young: true, adult: false, night: true, content: 'Descrption of Skulltula 4'},
  {id: 50, title: 'Secret Hole by the Great Fairy', location: 'Zora\'s Fountain', young: false, adult: true, night: true, content: 'Descrption of Skulltula 5'},
  {id: 51, title: 'Vine by the Water', location: 'Inside Jabu-Jabu\'s Belly', young: true, adult: false, night: false, content: 'Descrption of Skulltula 1'},
  {id: 52, title: 'Bottom of the Unblocked Hole', location: 'Inside Jabu-Jabu\'s Belly', young: true, adult: false, night: false, content: 'Descrption of Skulltula 2'},
  {id: 53, title: 'Near Big Octo\'s Chamber', location: 'Inside Jabu-Jabu\'s Belly', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 54, title: 'On the Vines before Barinade', location: 'Inside Jabu-Jabu\'s Belly', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 55, title: 'Soil by the Lakeside Laboratory', location: 'Lake Hylia', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 56, title: 'Behind the Lakeside Laboratory', location: 'Lake Hylia', young: true, adult: false, night: true, content: 'Descrption of Skulltula 1'},
  {id: 57, title: 'Pillars by the Fire Arrows', location: 'Lake Hylia', young: true, adult: false, night: true, content: 'Descrption of Skulltula 2'},
  {id: 58, title: 'On Top of the Dead Tree', location: 'Lake Hylia', young: false, adult: true, night: true, content: 'Descrption of Skulltula 3'},
  {id: 59, title: 'Pool in Lakeside Laboratory', location: 'Lake Hylia', young: false, adult: true, night: true, content: 'Descrption of Skulltula 4'},
  {id: 60, title: 'Vine by the Entrance to the Temple', location: 'Forest Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
  {id: 61, title: 'Right of the Northern Door', location: 'Forest Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 62, title: 'By the Chest in the Eastern Courtyard', location: 'Forest Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 63, title: 'High Wall in the Western Courtyard', location: 'Forest Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 3'},
  {id: 64, title: 'Behind the Rotating Wall', location: 'Forest Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 4'},
  {id: 65, title: 'Room Behind the Stone of Time', location: 'Fire Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
  {id: 66, title: 'False Wall Among the Rolling Boulders', location: 'Fire Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 67, title: 'High Elevator Above the Maze', location: 'Fire Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 68, title: 'Wall of the Circular Room', location: 'Fire Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 3'},
  {id: 69, title: 'Room with the Flying Tiles', location: 'Fire Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 4'},
  {id: 70, title: 'On the Wall by the Compass', location: 'Ice Cavern', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
  {id: 71, title: 'Behind the Stalagmites by the Spinning Blade', location: 'Ice Cavern', young: false, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 72, title: 'Wall by the Ice Blocks', location: 'Ice Cavern', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 73, title: 'Wall Behind the Switch', location: 'Water Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 3'},
  {id: 74, title: 'Wall Behind the Whirlpool', location: 'Water Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 4'},
  {id: 75, title: 'Top of the Central Room', location: 'Water Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
  {id: 76, title: 'Wall by the Moving Platforms', location: 'Water Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 77, title: 'Behind the Falling Rocks', location: 'Water Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 78, title: 'Behind the Like Like', location: 'Bottom of the Well', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 79, title: 'Small Room Behind the Locked Door', location: 'Bottom of the Well', young: true, adult: false, night: false, content: 'Descrption of Skulltula 4'},
  {id: 80, title: 'Locked Room with Invisible Floor', location: 'Bottom of the Well', young: true, adult: false, night: false, content: 'Descrption of Skulltula 5'},
  {id: 81, title: 'Wall by the Spinning Blade', location: 'Shadow Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 1'},
  {id: 82, title: 'Cell By the Falling Spikes', location: 'Shadow Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 83, title: 'Behind the Giant Skull Pot', location: 'Shadow Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 3'},
  {id: 84, title: 'High Up By the Ferry', location: 'Shadow Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 4'},
  {id: 85, title: 'Behind the Three Giant Skull Pot', location: 'Shadow Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
  {id: 86, title: 'Rocky Wall By the Plank Bridge', location: 'Gerudo Valley', young: true, adult: false, night: true, content: 'Descrption of Skulltula 1'},
  {id: 87, title: 'Soil by the Cow', location: 'Gerudo Valley', young: true, adult: false, night: false, content: 'Descrption of Skulltula 2'},
  {id: 88, title: 'Behind the Carpenters\' Tent', location: 'Gerudo Valley', young: false, adult: true, night: true, content: 'Descrption of Skulltula 3'},
  {id: 89, title: 'Under the Rock Arch', location: 'Gerudo Valley', young: false, adult: true, night: true, content: 'Descrption of Skulltula 4'},
  {id: 90, title: 'On the Archery Range Target', location: 'Gerudo\'s Fortress', young: false, adult: true, night: true, content: 'Descrption of Skulltula 5'},
  {id: 91, title: 'Atop Gerudo\'s Fortress', location: 'Gerudo\'s Fortress', young: false, adult: true, night: true, content: 'Descrption of Skulltula 1'},
  {id: 92, title: 'Structure within the Wasteland', location: 'Haunted Wasteland', young: false, adult: true, night: false, content: 'Descrption of Skulltula 2'},
  {id: 93, title: 'Soil by the Temple', location: 'Desert Colossus', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 94, title: 'Tree in the Oasis', location: 'Desert Colossus', young: false, adult: true, night: true, content: 'Descrption of Skulltula 4'},
  {id: 95, title: 'Rock Platform in the Desert', location: 'Desert Colossus', young: false, adult: true, night: true, content: 'Descrption of Skulltula 5'},
  {id: 96, title: 'Iron Fence by the Keese', location: 'Spirit Temple', young: true, adult: false, night: false, content: 'Descrption of Skulltula 1'},
  {id: 97, title: 'Behind the Climbed Rocks', location: 'Spirit Temple', young: true, adult: false, night: false, content: 'Descrption of Skulltula 2'},
  {id: 98, title: 'Towards the Iron Knuckle', location: 'Spirit Temple', young: true, adult: false, night: false, content: 'Descrption of Skulltula 3'},
  {id: 99, title: 'Behind the Stone of Time', location: 'Spirit Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 4'},
  {id: 100, title: 'Upper Left Platform by the Statue', location: 'Spirit Temple', young: false, adult: true, night: false, content: 'Descrption of Skulltula 5'},
]

export default skulltulas;
